### PR TITLE
Add verbose option for JIRA plugin

### PR DESCRIPTION
**Pull request by badnetmask**
The Jira plugin is a little bit more verbose than I would like, so I added a flag to make it quieter. It will still be verbose by default, so it doesn't break previous expectations.
@sochotnicky -- would you please review?

### CODE REVIEW

**Comment by fabioxgn** [comment]
Thanks for the PR @badnetmask.

I think that it should be quiet by default and have a verbose option instead. These logs are good for debugging but once it is stable I don't think these logs would be of much use. What do you think @sochotnicky?

**Comment by sochotnicky** [comment]
Well I actually generally opt to have more logs - even after code is debugged it helps when there's weird behaviour. For example the JIRA plugin doesn't handle it well when some project disappears (since JIRA doesn't ignore it but starts throwing errors).

In a similar way just a short while ago I was wondering why my bot was taking a long time to reply - based on logs I could tell it was because bitly API was throwing errors. 

That said this change only applies to informational messages.Plus I can always set an env variable to make things more verbose. I agree if there's a switch it makes sense for it to be "debug" or "verbose" rather than "quiet"

**Comment by badnetmask** [comment]
> That said this change only applies to informational messages.Plus I can always set an env variable to make things more verbose. I agree if there's a switch it makes sense for it to be "debug" or "verbose" rather than "quiet"

Pushed and tested. Seems to be working for me.

Thanks for reviewing so quickly!

**Review by fabioxgn — APPROVED** [review]
LGTM

**Pull request merged**
